### ISSUE TITLE
pt file have some bug?

### ISSUE THREAD

**Issue by xtlSJTU** [RuishengSu/CAVE_DSA#2]
2024-07-31 15:01:30 INFO     Using device cuda
Traceback (most recent call last):
    net.load_state_dict(torch.load(args.model, map_location=device))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\myenv\Lib\site-packages\torch\serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\myenv\Lib\site-packages\torch\serialization.py", line 1262, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by RuishengSu** [comment]
Hi there, I am not sure if I could directly pinpoint where it went wrong. Did you double check if you have provided the correct file path model weights file. BTW, you could download the model weights on Zenodo: https://zenodo.org/records/15641964
